/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.charaken.demoproject

import com.charaken.demoproject.foo.FooApp

class App {
    val greeting: String
        get() {
            return FooApp().greeting
        }
}

fun main(args: Array<String>) {
    println(App().greeting)
}
